--- #YAML:1.0
name:                Mail-ClamAV
version:             "0.29_1"
abstract:            Perl extension for the clamav virus scanner
license:             perl
author:              
    - David P.C. Wollmann <converter42@gmail.com>
    - Scott Beck <sbeck@gossamer-threads.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
no_index:
    directory:
    - Inline
requires:     
    Inline:                        0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
